cluster:
  mkdir -p results/logs/{rule} &&
  sbatch
    --account={resources.account}
    --partition={resources.partition}
    --nodes={resources.nodes}
    --ntasks={threads}
    --mem={resources.mem}
    --time={resources.time}
    --job-name={rule}-{wildcards}
    --output=results/logs/{rule}/smk-{rule}-{wildcards}-{jobid}.out
    --mail-type=ALL
    --mail-user=jts.quest.notifications@gmail.com
default-resources:
  - account="b1042"
  - partition="genomics"
  - nodes=1
  - mem="5G"
  - time="01:00:00"
jobs: 300
restart-times: 0
max-jobs-per-second: 15
max-status-checks-per-second: 1
local-cores: 5
latency-wait: 60
keep-going: True
rerun-incomplete: False
printshellcmds: True
scheduler: greedy
use-conda: True
